name: Build Android APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixar o código e Dependências Ocultas
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: 2. Travar o .NET na versão correta
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: 3. Instalar Motor do Android
      run: dotnet workload install android

    - name: 3.5. Limpar cache e reabilitar dependências
      run: |
        PROJECT_FILE=$(find . -iname "*android*.csproj" | head -n 1)
        
        if [ -z "$PROJECT_FILE" ]; then
          echo "ERRO CRÍTICO: Não encontrei nenhum arquivo com 'Android' no nome."
          exit 1
        fi
        
        echo "Limpando cache para: $PROJECT_FILE"
        rm -rf "${{ github.workspace }}"/**/obj
        rm -rf "${{ github.workspace }}"/**/bin
        
        echo "Reabilitando dependências..."
        dotnet restore "$PROJECT_FILE" --force-evaluate

    - name: 4. Compilar SOMENTE o App Android
      run: |
        PROJECT_FILE=$(find . -iname "*android*.csproj" | head -n 1)
        
        if [ -z "$PROJECT_FILE" ]; then
          echo "ERRO CRÍTICO: Não encontrei nenhum arquivo com 'Android' no nome."
          exit 1
        fi
        
        echo "Sucesso! Encontrei: $PROJECT_FILE"
        dotnet publish "$PROJECT_FILE" -c Release -f net10.0-android --no-restore
        
    - name: 5. Salvar o instalador APK
      uses: actions/upload-artifact@v4
      with:
        name: UTMT-Android-App
        path: '**/*.apk'
